### ISSUE TITLE
Suggestion : add activation by Dhizuku

### ISSUE THREAD

**Issue by Dantoza** [RikkaApps/Shizuku#845] opened 2024-12-02 07:18 UTC
Would it, be possible to activate shizuku with dhizuku? Doesn't deviceOwner grant permissions, and shizuku needs a shell permisision so... would it be possible?

**Comment by Ermageeerd** [comment] 2024-12-07 06:37
Duplicate of #399.

**Closed** 2024-12-07 07:37 UTC
