### ISSUE TITLE
add device owner mode

### ISSUE THREAD

**Issue by dontknowhy** [RikkaApps/Shizuku#215] opened 2022-05-29 05:34 UTC
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:latest
- Mode: [adb, root]adb
- Android version:11
- Device: (optional)

**Logs:**
none
Related **full logcat**.

**Describe the bug:**
need device owner node like black room（小黑屋）
just a device owner mode
my black room is working fine even i restart my device
**Additional context:**
add device owner mode

**Comment by haruue** [comment] 2022-05-29 05:38
Duplicate of #91

**Closed by haruue** 2022-05-29 05:38 UTC
Labels: duplicate
